#!/bin/bash
if [ $# -eq 1 ];then
	command=$1
	if [ -e "/etc/sudoers.d/piget" ];then
		/show/description "Remove root permission to the web server"
		/string/removeLine "/etc/sudoers.d/piget" "www-data ALL=NOPASSWD: $command" 
		sed -i '/^$/d' "/etc/sudoers.d/piget"
		/show/file /etc/sudoers.d/piget
	fi
else
	/show/errorBox "Wrong arguments"
	/show/usage "nginxDeAuthorize command"
	/show/example "nginxDeAuthorize /sbin/reboot"
	/show/file /etc/sudoers.d/piget
fi