#!/bin/bash
/show/description "Install xdebug"
/system/install php5-xdebug

/show/listecho "Searching for xdebug.so" $OK
xdebug=$(find / -name xdebug.so)
/show/listecho "Founded it at $xdebug" $OK
/show/listecho "Generating /etc/php5/fpm/conf.d/20-xdebug.ini" $OK

cat <<EOF > /etc/php5/fpm/conf.d/20-xdebug.ini &&
zend_extension = $xdebug
xdebug.profiler_output_dir=/tmp
xdebug.profiler_output_name=cachegrind.out.%p
xdebug.profiler_enable_trigger=1
xdebug.profiler_enable=0
xdebug.remote_enable=true
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9001
xdebug.remote_handler=dbgp
xdebug.remote_autostart=0
EOF

/show/file /etc/php5/fpm/conf.d/20-xdebug.ini
/system/restart php5-fpm
