#!/bin/bash
/show/description "Install web server nginx"
/system/install nginx
/system/install php5-fpm

/show/listecho "Generate /etc/nginx/sites-enabled/default" $OK
cat <<\EOF > /etc/nginx/sites-enabled/default &&
server {
        listen   80;


        root /user/web;
        index index.php index.html index.htm;

        #See http://nginx.org/en/docs/http/server_names.html
        server_name "";

        location / {
                try_files $uri $uri/ /index.html;
        }

        error_page 404 /404.html;

        # pass the PHP scripts to FastCGI server listening on the php-fpm socket
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }
}
EOF
/show/file /etc/nginx/sites-enabled/default
/system/restart nginx
if [ ! -e /var/www/index.html ];then
	echo "Copy web files into /var/www/" > /var/www/index.html
	echo "<br>You can change folder by typing /do/nginx/dir newdir" >> /var/www/index.html
fi
mkdir /user/web

