#!/bin/bash
description "Remove root permission to the web server"

if [ $# -eq 1 ];then
	command=$1
	removeLine "/etc/sudoers.d/piget" "www-data ALL=NOPASSWD: $command" 
	sed -i '/^$/d' "/etc/sudoers.d/piget"
	echo "/etc/sudoers.d/piget"
	console
	cat /etc/sudoers.d/piget
	console
else
	errorBox "Wrong arguments"
	usage "nginxDeAuthorize command"
	example "nginxDeAuthorize /sbin/reboot"
	linebreak
	echo "/etc/sudoers.d/piget"
	echo "List of authorized commands"
	console
	cat /etc/sudoers.d/piget
	console
fi