#!/bin/bash
description "Install web server nginx"
apt-get update
installer nginx
messagebox "Install php"
installer php5-fpm

messagebox "Generating /etc/nginx/sites-enabled/default"
cat <<\EOF > /etc/nginx/sites-enabled/default &&
server {
        listen   80;


        root /usr/share/nginx/www;
        index index.php index.html index.htm;

        #See http://nginx.org/en/docs/http/server_names.html
        server_name "";

        location / {
                try_files $uri $uri/ /index.html;
        }

        error_page 404 /404.html;

        # pass the PHP scripts to FastCGI server listening on the php-fpm socket
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }
}
EOF
console
cat /etc/nginx/sites-enabled/default
console
restarter nginx