#!/bin/bash
description "Installing Bower (manage javascript repositories)"

messagebox "Use adafruit apt repositories for nodejs"
curl -sLS https://apt.adafruit.com/add | sudo bash
installer node
messagebox "Install bower globally"
npm install -g bower
