#!/bin/bash
/show/description "Adding http authentication"
/system/install apache2-utils
/system/makedir /user/config/nginx

#Create user in htpasswd
. /show/askUser "Username"
username=$USERANSWER
htpasswd -c /user/config/nginx/htpasswd $username

#Adding line inside nginx default configuration
/string/addAfterLineIfNotExists "/etc/nginx/sites-enabled/default" " include fastcgi_params;" "auth_basic_user_file /user/config/nginx/htpasswd;"
/string/addAfterLineIfNotExists "/etc/nginx/sites-enabled/default" " include fastcgi_params;" 'auth_basic "Restricted";'

/system/restart nginx
