#!/bin/bash
/show/description "Removing http authentication"

rm /user/config/nginx/htpasswd
/string/removeLine "/etc/nginx/sites-enabled/default" "auth_basic_user_file /user/config/nginx/htpasswd;"
/string/removeLine "/etc/nginx/sites-enabled/default" 'auth_basic "Restricted";'
/system/restart nginx
